### ISSUE TITLE
Probably worth renaming this variable to "player_count"

### ISSUE THREAD

**Issue by blinks** [KenKuhn/deep.sea#10]
https://github.com/KenKuhn/deep.sea/blob/819c1fb2e74a13276f9a87cb60fcf3ad2dc1018e/game.rb#L15

Ruby style guide recommends "snake_case" for symbols, methods, variables:
https://github.com/rubocop-hq/ruby-style-guide#snake-case-symbols-methods-vars

**Comment by KenKuhn** [comment]
Updated
