### ISSUE TITLE
Choose Player Count Bug

### ISSUE THREAD

**Issue by KenKuhn** [KenKuhn/deep.sea#12]
```
  def choosePlayerCount
    puts "How many people are playing?"
    @player_count = gets.chomp
      if @player_count.to_i != 2..6
        puts "Please choose a number between 2-6."
        input2 = gets.chomp
        @player_count = input2
      end
  end
```
broke when we subbed in "player_count"

@blinks Any idea why? Maybe just bad syntax to start with?

**Comment by blinks** [comment]
What do you mean by "broke"?

(Bug report etiquette in three parts: 1. how do you reproduce the bug, 2. what did you expect to happen, 3. what actually happened.)

**Comment by KenKuhn** [comment]
Broke = doesn't work the way it did before

1. The bug is reproduce by running the file in CL. It doesn't "break" the program, rather it isn't functioning as intended. It was working before we changed the name from `@input1` to `@player_count`

2. The goal of the `choosePlayerCount` section of code is to verify number of players. If the input is an interger between 2-6 it should move on to `player_info`. If not it should recursively (not included right now) ask for a number between 2-6.

3. What actually happens is that it accepts any answer for the first question and automatically moves on to the second question, where it again accepts any answer and then it moves on to `player_info`
